### ISSUE TITLE
ASIC flow tutorial link is broken

### ISSUE THREAD

**Issue by ted-xie** [cornell-brg/pymtl#186]
Hi,

[This link](http://www.csl.cornell.edu/courses/ece5745/handouts/ece5745-tut-asic-new.pdf) in your README.md is broken. Could one of the maintainers please update the link?

**Comment by cbatten** [comment]
Hi Ted, Thanks for your interest in PyMTL. As noted on the README PyMTLv2 is no longer maintained and indeed is deprecated. Please consider using PyMTL3 instead!

 - https://github.com/pymtl/pymtl3

There are some new tutorials on the ECE 5745 course webpage if you are interested:

 - https://www.csl.cornell.edu/courses/ece5745

Although keep in mind we are using the ece5745-2021 branch of the PyMTL3 ... it should be merged into master soon. Please also consider joining the pymtl-users mailing list and posting questions there instead of using GitHub issues.

 - https://groups.google.com/forum/#!forum/pymtl-users
